### PR TITLE
Modify search to include contacts

### LINKED ISSUE #4789: Search by name doesn't work for all contacts
As discussed on [Loomio](https://www.loomio.org/d/KPmd4Nng/should-search-display-non-searchable-profiles-if-they-are-contacts), currently if a contact selects not to be searchable throughout the network in his privacy settings he will not show up when searching by name. Since we can see the names of our contacts, after adding them (or being added by them) we should be able to search for them by name.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1415887-search-by-name-doesn-t-work-for-all-contacts?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F522&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by svbergerem**
Fixes #4789 and #6787.

### CODE REVIEW

File: app/models/person.rb [hunk 1]
```diff
@@ -155,6 +155,18 @@ def self.search(query, user)
     ).includes(:profile).order(search_order)
   end
 
+  def self.contacts_search(query, user)
+    return where("1 = 0") if query.to_s.blank? || query.to_s.length < 2
```
Comment (jhass) [inline app/models/person.rb]: http://devdocs.io/rails~4.2/activerecord/querymethods#method-i-none

`query.blank?`, it's defined everywhere. Use `size` over `length`.

File: app/models/person.rb [hunk 2]
```diff
@@ -155,6 +155,18 @@ def self.search(query, user)
...
+
+    sql, tokens = search_query_string(query)
+
+    Person.joins(:contacts)
+          .where(contacts: {user_id: user.id})
+          .where(sql, *tokens)
+          .includes(:profile)
+          .order(search_order)
```
Comment (jhass) [inline app/models/person.rb]: So the only difference here to `search` is that it doesn't include people with `searchable: true`. I feel like this could be less redundant, perhaps just a keyword argument to `search`?

```rb
def self.search(query, user, only_contacts: false)
# ...
  query = Person
  query = query.searchable(user) unless only_contacts
  #....

File: app/controllers/contacts_controller.rb [hunk 3]
```diff
@@ -13,13 +13,17 @@ def index
...
 
-      # Used to populate mentions in the publisher
-      format.json {
-        aspect_ids = params[:aspect_ids] || current_user.aspects.map(&:id)
-        @people = Person.all_from_aspects(aspect_ids, current_user).for_json
-        render :json => @people.to_json
-      }
+    respond_to do |format|
+      format.json do
+        @people = @people.limit(15)
```
Comment (Flaburgan) [inline app/controllers/contacts_controller.rb]: Does the rails limit works like the SQL limit (meaning it only truncates result at the end but the load is still heavy?)

Comment (jhass) [inline app/controllers/contacts_controller.rb]: http://devdocs.io/rails~4.2/activerecord/querymethods#method-i-limit

**Comment by jhass** [comment]
Thank you!
